##
## InboxItem
##
## One actionable message in the manager's inbox — the core FM interaction
## loop. Board demands, press questions, player complaints, scout reports and
## contract alerts all arrive as one of these.
##
## An item with options is a decision: answering it applies that option's
## effects (morale, trust, board confidence, press reputation) and writes a
## WorldEvent. An item with no options is a notification and is merely read.
##
## Items expire. An unanswered decision past its deadline resolves itself with
## the escalation branch, which is always worse than any answer the manager
## could have given — ignoring a player is a choice.
##
## Depends on: CareerDate.
## Exposes: the fields below, make(), add_option(), is_expired(),
##          days_left(), option_count(), get_option().
##

class_name InboxItem
extends Resource

enum Category {
	BOARD = 0,
	MEDIA = 1,
	PLAYER = 2,
	STAFF = 3,
	TRANSFER = 4,
	CONTRACT = 5,
	FIXTURE = 6,
	TRAINING = 7,
	SCOUTING = 8,
	LEAGUE = 9,
	YOUTH = 10,
	FINANCE = 11,
}

const CATEGORY_NAMES: Array[String] = [
	"Board", "Media", "Player", "Staff", "Transfer", "Contract",
	"Fixture", "Training", "Scouting", "League", "Youth", "Finance"
]

const CATEGORY_ICONS: Array[String] = [
	"🏛", "🎤", "👤", "🧑‍🏫", "🔁", "📝", "📅", "🏃", "🔍", "🏆", "🌱", "💷"
]


## One selectable response. Effects are declarative deltas applied by
## InboxEngine.resolve() — an option never reaches into game state itself, so
## the same option data can be previewed in the UI before it is chosen.
class Option:
	var label: String = ""
	## Shown under the label as the expected consequence, FM-style.
	var hint: String = ""
	var squad_morale_delta: float = 0.0
	var subject_morale_delta: float = 0.0
	var board_confidence_delta: float = 0.0
	var manager_reputation_delta: float = 0.0
	## Trust between the manager and the subject player.
	var subject_trust_delta: float = 0.0
	## Press reputation: how favourably the media frames this manager.
	var press_standing_delta: float = 0.0
	## Free-form tag the resolving system switches on for structural effects
	## (accept a transfer, approve a budget request, promise playing time).
	var action_tag: StringName = &""
	var narrative: String = ""


@export var subject: String = ""
@export var body: String = ""
@export var category: Category = Category.BOARD
@export var received: CareerDate = null
## null = never expires.
@export var deadline: CareerDate = null
@export var is_read: bool = false
@export var is_resolved: bool = false
@export var chosen_option: int = -1
## team*1000+squad_index of the player this concerns, or -1.
@export var subject_player_key: int = -1
@export var subject_player_name: String = ""
## Higher sorts to the top of the inbox.
@export_range(0.0, 1.0) var priority: float = 0.4
## Index into the option list applied automatically if the deadline passes.
@export var escalation_option: int = -1
## Opaque payload for structural items (a transfer offer id, a fixture id).
@export var payload: Dictionary = {}

## Not @export-ed: Option is a plain inner class, so options are rebuilt from
## the serialised `payload`/generator rather than stored. Items that outlive a
## save are regenerated by InboxEngine; see CareerSerializer's note on this.
var options: Array[Option] = []


static func make(p_subject: String, p_body: String, p_category: Category, p_received: CareerDate) -> InboxItem:
	var item := InboxItem.new()
	item.subject = p_subject
	item.body = p_body
	item.category = p_category
	item.received = p_received.copy() if p_received != null else null
	return item


func add_option(
	label: String,
	hint: String,
	action_tag: StringName = &"",
	squad_morale: float = 0.0,
	subject_morale: float = 0.0,
	board_conf: float = 0.0,
	press: float = 0.0
) -> InboxItem:
	var o := Option.new()
	o.label = label
	o.hint = hint
	o.action_tag = action_tag
	o.squad_morale_delta = squad_morale
	o.subject_morale_delta = subject_morale
	o.board_confidence_delta = board_conf
	o.press_standing_delta = press
	options.append(o)
	return self


func with_subject_player(key: int, display_name: String) -> InboxItem:
	subject_player_key = key
	subject_player_name = display_name
	return self


func with_deadline(d: CareerDate, escalate_to: int = -1) -> InboxItem:
	deadline = d.copy() if d != null else null
	escalation_option = escalate_to
	return self


func with_priority(p: float) -> InboxItem:
	priority = clampf(p, 0.0, 1.0)
	return self


func option_count() -> int:
	return options.size()


func get_option(index: int) -> Option:
	if index < 0 or index >= options.size():
		return null
	return options[index]


func requires_decision() -> bool:
	return not is_resolved and not options.is_empty()


func is_expired(today: CareerDate) -> bool:
	if deadline == null or today == null:
		return false
	return deadline.is_before(today)


func days_left(today: CareerDate) -> int:
	if deadline == null or today == null:
		return 9999
	return today.days_until(deadline)


func category_name() -> String:
	return CATEGORY_NAMES[clampi(int(category), 0, CATEGORY_NAMES.size() - 1)]


func category_icon() -> String:
	return CATEGORY_ICONS[clampi(int(category), 0, CATEGORY_ICONS.size() - 1)]
